name: Simple DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Secret Scan
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v2
        continue-on-error: true

      # Code Scan
      - name: Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "auto"
        continue-on-error: true

      #Dependency Scan
      - name: Trivy FS
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
        continue-on-error: true

      # Build Image
      - name: Build Docker Image
        run: docker build -t myapp .

      #Image Scan
      - name: Trivy Image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: myapp
        continue-on-error: true

      # Login Docker Hub
      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push Image
      - name: Tag
        run: docker tag myapp ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
